version: '3.7'

services:
  server-grpc:
    container_name: server-grpc 
    build:
      context: ./server-grpc
      dockerfile: Dockerfile  
    ports:
      - '50051:50051'
    command: yarn start

  client-grpc:
    container_name: client-grpc
    build:
      context: ./client-grpc
      dockerfile: Dockerfile  
    ports:
      - '3000:3000'
    command: yarn start